### ISSUE TITLE
error on npm install stanza.io

### ISSUE THREAD

**Issue by EvilJinious1** [legastero/stanza.io#256]
I get this on performing the npm install stanza.io
Something I am missing?
--------------------------------------------------------------------
(local) MLA0RLI094:chatproject larry.mitchell$ npm install stanza.io

> node-stringprep@0.8.0 install /Users/larry.mitchell/chatproject/node_modules/node-stringprep
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: self signed certificate in certificate chain
gyp ERR! stack     at TLSSocket.onConnectSecure (_tls_wrap.js:1046:34)
gyp ERR! stack     at TLSSocket.emit (events.js:180:13)
gyp ERR! stack     at TLSSocket._finishInit (_tls_wrap.js:633:8)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/larry.mitchell/chatproject/node_modules/node-stringprep
gyp ERR! node -v v9.9.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN saveError ENOENT: no such file or directory, open '/Users/larry.mitchell/chatproject/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/larry.mitchell/chatproject/package.json'
npm WARN chatproject No description
npm WARN chatproject No repository field.
npm WARN chatproject No README data
npm WARN chatproject No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-stringprep@0.8.0 (node_modules/node-stringprep):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-stringprep@0.8.0 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ stanza.io@9.0.2
updated 1 package in 2.739s

**Comment by EvilJinious1** [comment]
Exporting NODE_TLS_REJECT_UNAUTHORIZED=0 gets pass this.  
The current build is a bit of a mess
