### ISSUE TITLE
make-better dependency

### ISSUE THREAD

**Issue by trickpattyFH20** [legastero/stanza.io#98]
So the make file does not work for me, through further investigation, I was missing some of the dependencies for stanza.io lister here: https://www.versioneye.com/nodejs/stanza.io/7.1.8

when trying to install the make-better package, I get an error, it seems like something is wrong with the make-better package, I'll post the error message below.

**Can somebody help me figure out how to get the current built version of stanza.io? maybe by posting a link to folder containing a built version, or maybe the creators would consider not using the make-better library?**

$ sudo npm install make-better  --save-dev
\

> make-better@0.4.2 install /Users/Patrick/node_modules/make-better
> node install.js

/Users/Patrick/node_modules/make-better/node_modules/git-validate/lib/utils.js:154
        throw new Error('Unable to find a package.json for this project');
              ^
Error: Unable to find a package.json for this project
    at Object.exports.findProjectRoot (/Users/Patrick/node_modules/make-better/node_modules/git-validate/lib/utils.js:154:15)
    at Object.exports.findProjectRoot (/Users/Patrick/node_modules/make-better/node_modules/git-validate/lib/utils.js:158:24)
    at Object.exports.findProjectRoot (/Users/Patrick/node_modules/make-better/node_modules/git-validate/lib/utils.js:158:24)
    at Object.exports.copy (/Users/Patrick/node_modules/make-better/node_modules/git-validate/lib/utils.js:48:31)
    at Object.<anonymous> (/Users/Patrick/node_modules/make-better/install.js:2:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "make-better" "--save-dev"
npm ERR! node v0.12.2
npm ERR! npm  v2.8.4
npm ERR! code ELIFECYCLE

npm ERR! make-better@0.4.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the make-better@0.4.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the make-better package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls make-better
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Patrick/npm-debug.log

**Comment by legastero** [comment]
Run `npm install` first to get all of the dependencies, and then the `Makefile` should work.

**Comment by trickpattyFH20** [comment]
gosh, I should have figured that out. I need to get better at using node + npm. got my build working. thank you very much

**Comment by amanraghubansi** [comment]
I don't want to run commands 1. npm install inside node_modules/stanza.io 2. make.....
How can i directly get build stanza file.
